In [1]:
import numpy as np

In [2]:
a1 = np.arange(5)

In [3]:
a1

array([0, 1, 2, 3, 4])

In [4]:
a2 = np.random.randint(1,5,(2,5))

In [5]:
a2

array([[2, 4, 1, 3, 2],
       [4, 1, 1, 2, 4]])

In [6]:
# comparison

In [7]:
a1 > a2

array([[False, False,  True, False,  True],
       [False, False,  True,  True, False]])

In [8]:
a2 < a1

array([[False, False,  True, False,  True],
       [False, False,  True,  True, False]])

In [9]:
a1 == a2

array([[False, False, False,  True, False],
       [False,  True, False, False,  True]])

In [10]:
a1 >= a2

array([[False, False,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [11]:
a2 <= a2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [12]:
a1 == a1

array([ True,  True,  True,  True,  True])

In [22]:
### Sorting array (values)

In [15]:
b1 = np.random.randint(20,size=(2,5))

In [16]:
b1

array([[ 4,  5, 16,  6, 18],
       [ 0,  6,  5,  5, 16]])

In [17]:
b1.shape

(2, 5)

In [18]:
np.sort(b1)

array([[ 4,  5,  6, 16, 18],
       [ 0,  5,  5,  6, 16]])

In [20]:
a2

array([[2, 4, 1, 3, 2],
       [4, 1, 1, 2, 4]])

In [21]:
np.sort(a2)

array([[1, 2, 2, 3, 4],
       [1, 1, 2, 4, 4]])

In [23]:
# sorting index

In [24]:
a2

array([[2, 4, 1, 3, 2],
       [4, 1, 1, 2, 4]])

In [25]:
np.argsort(a2)

array([[2, 0, 4, 3, 1],
       [1, 2, 3, 0, 4]], dtype=int64)

In [26]:
a1

array([0, 1, 2, 3, 4])

In [27]:
np.argsort(a1)

array([0, 1, 2, 3, 4], dtype=int64)

In [28]:
np.argmin(a1)

0

In [32]:
np.argmin(a2,axis=0)

array([0, 1, 0, 1, 0], dtype=int64)

In [33]:
np.argmax(a2,axis=1)

array([1, 0], dtype=int64)

In [31]:
np.argmax(a1)

4