In [2]:
import numpy as np

In [2]:
#intro to numpy

In [3]:
f1_array = np.array([1,2,3])

In [4]:
f1_array

array([1, 2, 3])

In [5]:
f1_array.size

3

In [6]:
type(f1_array)

numpy.ndarray

In [7]:
##

In [8]:
f2_array = np.array([ [1,2,3],
                    [2,3,5]])

In [9]:
f3_array = np.array([ [[1,2,3],
                        [2,3,4],
                            [5,4,3]],
                     [[3,4,5],
                         [6,4,2],
                         [6,2,3]]
                    ])

In [10]:
f2_array

array([[1, 2, 3],
       [2, 3, 5]])

In [11]:
f3_array

array([[[1, 2, 3],
        [2, 3, 4],
        [5, 4, 3]],

       [[3, 4, 5],
        [6, 4, 2],
        [6, 2, 3]]])

In [17]:
[3] #scaler

[3]

In [18]:
f1_array #1 dim #vector

array([1, 2, 3])

In [19]:
f2_array #2 dim #matrix

array([[1, 2, 3],
       [2, 3, 5]])

In [20]:
f3_array # 3 dim tensor

array([[[1, 2, 3],
        [2, 3, 4],
        [5, 4, 3]],

       [[3, 4, 5],
        [6, 4, 2],
        [6, 2, 3]]])

In [21]:
#attribute

In [22]:
f1_array.shape

(3,)

In [23]:
f2_array.shape

(2, 3)

In [24]:
f3_array.shape

(2, 3, 3)

In [25]:
f1_array.ndim

1

In [26]:
f2_array.ndim

2

In [27]:
f3_array.ndim

3

In [28]:
f1_array.size

3

In [29]:
f2_array.size

6

In [30]:
f3_array.size

18

In [31]:
# numpy DataFrame
import pandas as pd

In [32]:
df2 = pd.DataFrame(f2_array)

In [33]:
df2

0  1  2
0  1  2  3
1  2  3  5

In [34]:
### creating numpy array

In [35]:
#auto generate number by numpy

In [40]:
one_array = np.ones((2,3)) 

In [41]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
one_array.dtype

dtype('float64')

In [43]:
type(one_array)

numpy.ndarray

In [44]:
zero_array = np.zeros((2,3))

In [45]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
#range numpy

In [48]:
np.arange(0,10,2) #evenly distribute

array([0, 2, 4, 6, 8])

In [50]:
np.random.randint(1,10, size=(2,3))

array([[7, 3, 1],
       [1, 8, 2]])

In [52]:
np.random.random((2,4))

array([[0.34095778, 0.71917664, 0.46922245, 0.83869596],
       [0.04585637, 0.72241913, 0.37580226, 0.93796421]])

In [54]:
np.random.rand(3,3)

array([[0.42522286, 0.91333953, 0.25217543],
       [0.87750818, 0.98364231, 0.07610436],
       [0.97703488, 0.69374038, 0.57801747]])

In [1]:
#####################getting unique array ################################

In [5]:
np.random.seed(7)
random_arr = np.random.randint(1,20,(4,3))

In [6]:
random_arr

array([[16,  5,  4],
       [ 8, 15,  9],
       [15, 11,  9],
       [ 8,  7,  5]])

In [7]:
np.unique(random_arr)

array([ 4,  5,  7,  8,  9, 11, 15, 16])