In [1]:
import numpy as np

In [2]:
np.random.seed(1)
rand1 = np.random.randint(1,10,(2,3))

In [3]:
rand1

array([[6, 9, 6],
       [1, 1, 2]])

In [4]:
np.random.seed(2)
rand2 = np.random.randint(1,10,(2,3,3))

In [5]:
rand2

array([[[9, 9, 7],
        [3, 9, 8],
        [3, 2, 6]],

       [[5, 5, 6],
        [8, 4, 7],
        [5, 4, 8]]])

In [6]:
################
#Elements showing

In [7]:
rand1[0]

array([6, 9, 6])

In [8]:
rand2[0]

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6]])

In [9]:
rand1[1]

array([1, 1, 2])

In [10]:
rand2[1]

array([[5, 5, 6],
       [8, 4, 7],
       [5, 4, 8]])

In [11]:
rand1.shape 

(2, 3)

In [12]:
rand2.shape

(2, 3, 3)

In [13]:
#slice

In [14]:
rand2

array([[[9, 9, 7],
        [3, 9, 8],
        [3, 2, 6]],

       [[5, 5, 6],
        [8, 4, 7],
        [5, 4, 8]]])

In [17]:
rand2[:2,:2,:2]

array([[[9, 9],
        [3, 9]],

       [[5, 5],
        [8, 4]]])

In [18]:
########### 4dim array

In [19]:
rand4 = np.random.randint(1,10,(3,2,4,4))

In [20]:
rand4

array([[[[7, 2, 4, 6],
         [9, 5, 7, 4],
         [3, 1, 5, 3],
         [5, 2, 8, 9]],

        [[3, 9, 8, 2],
         [7, 9, 6, 4],
         [1, 1, 3, 9],
         [9, 3, 7, 6]]],


       [[[7, 7, 7, 4],
         [9, 3, 2, 5],
         [9, 2, 7, 6],
         [2, 3, 5, 8]],

        [[7, 5, 6, 9],
         [4, 1, 1, 6],
         [8, 6, 1, 9],
         [7, 6, 2, 8]]],


       [[[5, 4, 7, 2],
         [5, 1, 9, 6],
         [5, 3, 8, 2],
         [3, 2, 1, 8]],

        [[2, 9, 1, 8],
         [1, 6, 3, 6],
         [2, 4, 4, 2],
         [9, 7, 9, 2]]]])

In [21]:
rand4.shape

(3, 2, 4, 4)

In [22]:
rand4.ndim

4

In [23]:
rand4[:,:,:,:2]

array([[[[7, 2],
         [9, 5],
         [3, 1],
         [5, 2]],

        [[3, 9],
         [7, 9],
         [1, 1],
         [9, 3]]],


       [[[7, 7],
         [9, 3],
         [9, 2],
         [2, 3]],

        [[7, 5],
         [4, 1],
         [8, 6],
         [7, 6]]],


       [[[5, 4],
         [5, 1],
         [5, 3],
         [3, 2]],

        [[2, 9],
         [1, 6],
         [2, 4],
         [9, 7]]]])