In [1]:
import numpy as np

In [3]:
np.random.seed(1)
a1 = np.random.randint(1,10,(4,2))
a2 = np.random.randint(1,10,(2,4))

In [4]:
a1

array([[6, 9],
       [6, 1],
       [1, 2],
       [8, 7]])

In [5]:
a2

array([[3, 5, 6, 3],
       [5, 3, 5, 8]])

In [6]:
a1.shape,a2.shape

((4, 2), (2, 4))

In [7]:
a1 * a2.T # Element Wise 

array([[18, 45],
       [30,  3],
       [ 6, 10],
       [24, 56]])

In [8]:
# Dot Product

In [10]:
np.dot(a1,a2) # (4,2) dotproduct (2,4) = (4,4)

array([[63, 57, 81, 90],
       [23, 33, 41, 26],
       [13, 11, 16, 19],
       [59, 61, 83, 80]])

In [11]:
# (a,b) dot product of (b,a) will be (a,a)

In [13]:
a3 = np.random.randint(1,10,(3,2,2))

In [14]:
a4 = np.random.randint(1,10,(3,2,2))

In [15]:
a3

array([[[8, 2],
        [8, 1]],

       [[7, 8],
        [7, 2]],

       [[1, 2],
        [9, 9]]])

In [16]:
a4

array([[[4, 9],
        [8, 4]],

       [[7, 6],
        [2, 4]],

       [[5, 9],
        [2, 5]]])

In [17]:
(a3.shape),(a4.shape)

((3, 2, 2), (3, 2, 2))

In [19]:
np.dot(a3,a4).shape

(3, 2, 3, 2)

In [20]:
np.dot(a3,a4)

array([[[[ 48,  80],
         [ 60,  56],
         [ 44,  82]],

        [[ 40,  76],
         [ 58,  52],
         [ 42,  77]]],


       [[[ 92,  95],
         [ 65,  74],
         [ 51, 103]],

        [[ 44,  71],
         [ 53,  50],
         [ 39,  73]]],


       [[[ 20,  17],
         [ 11,  14],
         [  9,  19]],

        [[108, 117],
         [ 81,  90],
         [ 63, 126]]]])

In [32]:
a5 = np.random.randint(1,10,(4,3,2))

In [33]:
np.dot(a5,a4).shape

(4, 3, 3, 2)

In [34]:
a5.shape , a4.shape

((4, 3, 2), (3, 2, 2))

In [35]:
np.dot(a5,a4)

array([[[[108, 117],
         [ 81,  90],
         [ 63, 126]],

        [[ 76,  59],
         [ 37,  50],
         [ 31,  67]],

        [[ 72,  78],
         [ 54,  60],
         [ 42,  84]]],


       [[[ 68,  69],
         [ 47,  54],
         [ 37,  75]],

        [[ 84, 105],
         [ 75,  78],
         [ 57, 111]],

        [[ 52,  89],
         [ 67,  62],
         [ 49,  91]]],


       [[[ 80,  54],
         [ 32,  48],
         [ 28,  63]],

        [[ 40,  76],
         [ 58,  52],
         [ 42,  77]],

        [[ 56,  56],
         [ 38,  44],
         [ 30,  61]]],


       [[[ 20,  31],
         [ 23,  22],
         [ 17,  32]],

        [[ 64,  60],
         [ 40,  48],
         [ 32,  66]],

        [[ 32,  30],
         [ 20,  24],
         [ 16,  33]]]])