In [1]:
import numpy as np

In [2]:
r1 = np.random.randint(0,10)

In [3]:
r1

3

In [5]:
np.random.randint(0,10,3) # 0 to 10 and the size of the array is 3

array([8, 2, 2])

In [7]:
np.random.randint(0,10,(3,2)) #the size is (3,2) = total 6 # 3 rows 2 columns

array([[9, 5],
       [9, 2],
       [3, 6]])

In [8]:
#random.random

In [10]:
np.random.random(3) #return 3 values from 0 to 1 

array([0.7505197 , 0.49444099, 0.34282863])

In [12]:
np.random.random((2,3))

array([[0.48938182, 0.91222479, 0.66688397],
       [0.73542948, 0.29727496, 0.51473621]])

In [13]:
np.random.random((4,2))

array([[0.56800798, 0.73280645],
       [0.20368381, 0.35208986],
       [0.84613148, 0.96242972],
       [0.4136763 , 0.22337855]])

In [15]:
###rand

In [19]:
np.random.rand(2) #will return value from 0 to 1

array([0.95122217, 0.27672059])

In [21]:
np.random.rand(4,2)

array([[0.82919247, 0.06416216],
       [0.06105214, 0.54981258],
       [0.80749352, 0.73996813],
       [0.10477817, 0.67581676]])

In [22]:
#######################################

In [24]:
# Random digit always print new random values whenerver it runs the code
# To avoid this problem


In [25]:
################# RANDOM SEED 

In [29]:
np.random.seed(123) #any digit would give the same result seed(0) seed(1) seed(3)............
ran_seed = np.random.randint(0,10,(5,3))

In [30]:
ran_seed

array([[2, 2, 6],
       [1, 3, 9],
       [6, 1, 0],
       [1, 9, 0],
       [0, 9, 3]])

In [31]:
# this combinations will not change . it has the seed name = 123