In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(1,10,(2,3))

In [3]:
a1

array([[2, 8, 3],
       [8, 7, 6]])

In [4]:
a1.shape

(2, 3)

In [5]:
a2 = np.random.randint(1,10,(3,2))

In [6]:
a2

array([[2, 9],
       [3, 4],
       [5, 8]])

In [7]:
a2.shape

(3, 2)

In [8]:
(a1.shape), (a2.shape)

((2, 3), (3, 2))

In [11]:
# a1 + a2 boradcasting won't work as they both represnt different shape

### Reshape Array

In [12]:
a2.reshape(2,3)

array([[2, 9, 3],
       [4, 5, 8]])

In [13]:
a2.shape

(3, 2)

In [14]:
(a2.reshape(2,3)).shape

(2, 3)

In [15]:
a1 + a2.reshape(2,3)

array([[ 4, 17,  6],
       [12, 12, 14]])

In [16]:
a1.shape

(2, 3)

In [17]:
a2.shape

(3, 2)

In [18]:
a1.reshape(3,2)

array([[2, 8],
       [3, 8],
       [7, 6]])

In [19]:
a1.reshape(3,2) * a2

array([[ 4, 72],
       [ 9, 32],
       [35, 48]])

In [20]:
## Transpose

In [21]:
a1

array([[2, 8, 3],
       [8, 7, 6]])

In [22]:
a1.T

array([[2, 8],
       [8, 7],
       [3, 6]])

In [23]:
(a1.shape), (a1.T.shape)

((2, 3), (3, 2))

In [24]:
a1 + a2.T

array([[ 4, 11,  8],
       [17, 11, 14]])

In [25]:
a1.T + a2

array([[ 4, 17],
       [11, 11],
       [ 8, 14]])

In [26]:
a3 = np.random.randint(1,10,(2,3,3))

In [27]:
a3 

array([[[5, 2, 6],
        [2, 8, 3],
        [6, 9, 8]],

       [[5, 2, 6],
        [6, 3, 3],
        [6, 6, 1]]])

In [28]:
a3.T

array([[[5, 5],
        [2, 6],
        [6, 6]],

       [[2, 2],
        [8, 3],
        [9, 6]],

       [[6, 6],
        [3, 3],
        [8, 1]]])

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a3.T.shape

(3, 3, 2)

In [31]:
####################### 