In [1]:
import numpy as np
import pandas as pd

In [2]:
## soft drinks sales

In [3]:
np.random.seed(0)
drinks_sale = np.random.randint(30,size=(7,3))

In [4]:
drinks_sale

array([[12, 15, 21],
       [ 0,  3, 27],
       [ 3,  7,  9],
       [19, 21, 18],
       [ 4, 23,  6],
       [24, 24, 12],
       [26,  1,  6]])

In [5]:
weekly_sale = pd.DataFrame(drinks_sale,index=['Sat','Sun','Mon','Tue','Wed','Thur','Fri'],columns=['7up','Pepsi','Sprite'])

In [6]:
weekly_sale

7up  Pepsi  Sprite
Sat    12     15      21
Sun     0      3      27
Mon     3      7       9
Tue    19     21      18
Wed     4     23       6
Thur   24     24      12
Fri    26      1       6

In [7]:
bottle_price =np.array([30,35,25])

In [8]:
bottle_price

array([30, 35, 25])

In [9]:
#price DF

In [10]:
price = pd.DataFrame(bottle_price.reshape(1,3),index=['Price'],columns=['7up','Pepsi','Sprite'])

In [11]:
price

7up  Pepsi  Sprite
Price   30     35      25

In [12]:
### DoT Product ################################################################

In [13]:
bottle_price.shape

(3,)

In [14]:
drinks_sale.shape

(7, 3)

In [15]:
drinks_sale.T.shape

(3, 7)

In [16]:
bottle_price.dot(drinks_sale.T)

array([1410,  780,  560, 1755, 1075, 1860,  965])

In [17]:
bottle_price

array([30, 35, 25])

In [18]:
bottle_price.reshape(1,3).shape

(1, 3)

In [19]:
drinks_sale.T.shape

(3, 7)

In [20]:
np.dot(bottle_price.reshape(1,3),drinks_sale.T) #(1,3) dot (3,7) will be (1,7)

array([[1410,  780,  560, 1755, 1075, 1860,  965]])

In [21]:
##############################################################################

In [22]:
weekly_sale

7up  Pepsi  Sprite
Sat    12     15      21
Sun     0      3      27
Mon     3      7       9
Tue    19     21      18
Wed     4     23       6
Thur   24     24      12
Fri    26      1       6

In [23]:
price

7up  Pepsi  Sprite
Price   30     35      25

In [24]:
weekly_sale.shape

(7, 3)

In [25]:
price.shape

(1, 3)

In [26]:
price.dot(weekly_sale.T)

Sat  Sun  Mon   Tue   Wed  Thur  Fri
Price  1410  780  560  1755  1075  1860  965

In [30]:
Total = price.dot(weekly_sale.T)

In [31]:
Total

Sat  Sun  Mon   Tue   Wed  Thur  Fri
Price  1410  780  560  1755  1075  1860  965

In [32]:
sales = weekly_sale.copy()

In [33]:
sales

7up  Pepsi  Sprite
Sat    12     15      21
Sun     0      3      27
Mon     3      7       9
Tue    19     21      18
Wed     4     23       6
Thur   24     24      12
Fri    26      1       6

In [34]:
sales.shape

(7, 3)

In [36]:
Total.shape

(1, 7)

In [38]:
np.array(Total)

array([[1410,  780,  560, 1755, 1075, 1860,  965]])

In [42]:
sales['Total'] = np.array(Total).T

In [43]:
sales

7up  Pepsi  Sprite  Total
Sat    12     15      21   1410
Sun     0      3      27    780
Mon     3      7       9    560
Tue    19     21      18   1755
Wed     4     23       6   1075
Thur   24     24      12   1860
Fri    26      1       6    965

In [44]:
sales['Total(T)'] = Total.T

In [45]:
sales

7up  Pepsi  Sprite  Total  Total(T)
Sat    12     15      21   1410      1410
Sun     0      3      27    780       780
Mon     3      7       9    560       560
Tue    19     21      18   1755      1755
Wed     4     23       6   1075      1075
Thur   24     24      12   1860      1860
Fri    26      1       6    965       965

In [48]:
sales.drop('Total(T)',axis=1)

7up  Pepsi  Sprite  Total
Sat    12     15      21   1410
Sun     0      3      27    780
Mon     3      7       9    560
Tue    19     21      18   1755
Wed     4     23       6   1075
Thur   24     24      12   1860
Fri    26      1       6    965

In [49]:
sales.to_csv('drinks_sale.csv',index=False)